### ISSUE TITLE
Project Demonstration 1 - Reflections

### ISSUE THREAD

**Issue by majo22wx** [Kiopp/Dungeon-Crawler-Game#90]
Submit your reflections in the comments below.

**Comment by majo22wx** [comment]
#### Chapter 1: The Problem of Delivering Software
One of the main ideas is to automate almost everything. Automating testing, building and deployment will ease a lot of pain especially for bigger projects.
It’s important to avoid long life branches. Keep everything in version control, not just code.
The main goal of the chapter is raise concepts which help avoid a tense, rocky and uncertain launch day.

#### Chapter 2: Endless Configurability 
Commit often and don’t leave branches for too long because merging will be difficult.
Configurability can lead to infinite devtime. Manage configurability carefully. It’s not bad to have configurability but it’s more important to have less functionality of higher quality.

#### Chapter 3: Continuous is More Often Than You Think
We have implemented a lot of what is described in the chapter. Although the chapter focuses on slightly different a slightly different use case and project size. Once again it pushes for not leaving long life branches. Push working code to main often. Preferable to do run unit tests locally before pushing to the repo, but in our case using github feels faster. 
Main takeaway is the focus ”Continuous” in Continuous Integration, commit often and get your code working on main.

#### Chapter 4: Testing
Their story is that you should write and acceptance tests that will pass once you have written sufficient functional code. 
80% code coverage is a good goal for unit testing. 
Code coverage should be wide enough that swapping a major component should feel safe as long as the test pass.

#### Chapter 14: Working with Modern Version Control Systems
We shouldn’t forget what a blessing version control really is today. I have worked in a setting where people need to access files from a file server at the same time. Where files will be locked while one person is accessing it, sometimes files become perpetually locked because of a bug or someone not logging out.  Simultaneously being able to access and modify a version of the same file and then merge the changes is incredible.
Many times throughout these chapters they speak of branching as if it were the devil and I understand why it clashes with the idea CI. Checking in your code at least once a day is often enough that the concept of CI holds up. Checking in less often and keeping many branches alive will lead to long integration periods and periods of broken main. Only release branches should be long life.
This chapter is refenced throughout the other chapters, and it feels like the most relevant information to our project.

**Comment by Vencilo** [comment]
The first chapter describes the advantages of having an automated process and how it works. It could help us reduce errors and mistakes and find these errors along the way so that all errors do not come at the same time when we are finished. It can also help us to make the testing easier and faster.
The second chapter describes configuration management. It could help us make sure that we all use the same environment, so we do not get errors because the parts of the code are adapted to a different environment. It could also make sure we can go back to a previous version of our project if needed to help with the process of the project.
The third chapter describes continuous integration. This can help to make sure the project is up to date and that everyone working on the project is up to speed all the time. It also helps finding errors earlier in development and makes sure the project can be compiled/built through the entire process instead of only finding out if it is or is not at the end.
The fourth chapter describes the importance of testing strategy and discipline. It is important to test regularly and throughout the entire process of development to find as many errors as possible and as fast as possible to be able to fix them as soon as possible. It is also important to have high quality tests and different types of tests to properly test the entire project. This could help us in our project to overcome problems faster and more easily but also find and fix errors quickly to have a smooth process.
The book has argued that branching is not very good in software development because it can lead to a bunch of different problems. It can make it problem some with continuous integration and can sometimes be difficult to merge a branch with the main. I can understand their points, but I believe it works well in our project since it is very small, and we are not many people working on it. We do not have to commit or merge as often as you would do in bigger projects because we do not have as many changes so once per day roughly would suffice for us.
Chapter 1: An automated process can reduce costs, time, resources, errors, increase reliability and in general make the process easier.
Chapter 2: Configuration management is a core part of good software development. It makes other important it makes other approaches possible like continuous integration, release management and deployment pipelining.
Chapter 3: Continuous integration is a great way to keep everything up to speed and find errors earlier and along the way as the project develops.
Chapter 4: Testing strategy and discipline is very important to test the entire project properly and regularly to avoid a lot of errors at the same time and always have a functioning project.
Chapter 14: It is not just important to have a version control but also to have a good version control and use it well.

**Comment by CarlNord01** [comment]
Chapter one highlights the importance of automated build and deployments and that consistent and automated processes are foundational to scaling up project size without compromising quality.

Chapter two talks about configuration management and illustrates how centralizing code and assets can simplify coordination and ensuring everything is consistent across different development environments. I can also see how this becomes more and more as team sizes grow.

Chapter three discusses the significance of continuous integration in catching integration issues early, ensuring that new features integrate well without disrupting existing functionality. This is also useful as it involves smaller, more manageable changes that can be easily tracked.

Chapter four focuses on automating acceptance testing, which can be crucial for ensuring that a game meets all specified requirements and behaving as intended under various circumstances. This will be really helpful when our game grows in size, ensuring that everything is working as intended.

Chapter 14 is focusing on version control and configuration management demonstrating how effective control can aid scalability and team collaboration in larger projects. It is really helpful in game development for managing features and experiments without disrupting the main development line, ensuring that everything is properly documented and integrated.

Main Takeaways:
Chapter 1: Automation of builds and deployments is key to maintaining quality as projects scale.
Chapter 2: Centralizing code and assets in a single source repository simplifies project management across larger teams.
Chapter 3: A strong testing culture with continuous integration is essential for managing complex project dynamics.
Chapter 4: Automated acceptance testing is critical for protecting the user experience during project expansions.
Chapter 14: Sophisticated version control systems and smart branching strategies for ensuring safe, reliable software releases.

**Comment by mowaab** [comment]
The ways that the literature from five mentioned chapters can be applicable to our project is firstly the importance of always keeping everything in version control. according to the author of the book, branching should be avoided in most situations, instead they recommend incrementally developing features and commiting them on a regular basis. The literature also states that it is important to always test throughout the development process and by everyone on the team, this can benefit the team by keeping everyone involved and improving the feedback loop. 

The insight that I have gained on working in larger from reading the chapters is that automation is crucial to the development process by helping save time and reduce cost, it can allow for an improved work-life balance for the persons in the team. It also greatly reduces the risk of error. 

My main take-away from chapter 1 is the importance of automation and how automation can have a big impact on the time and cost of the whole development process. 

My main take-away from chapter 2 is that good configuration management is essential for projects, allowing for continuous integration, release management, deployment pipelining, and improving the collaboration within delivery teams. 

My main take-away from chapter 3 is that implementation of continuous integration can greatly enhance the productivity of team 

My main take-away from chapter 4 is that testing is a key part of the development process that should be done consistently throughout the whole process and that every team member should participate in testing. 

My main take-away from chapter 14 is the importance of version control systems and the use of the tools that are provided by version control.

**Comment by mtaromi** [comment]
@majo22wx: At some point, please take a look into Chapter 2 once again :)

**Comment by mtaromi** [comment]
@majo22wx, @Vencilo, @mowaab, @CarlNord01, and @Kiopp 

Nice reflections, well done!
